image:
  file: .gitpod.Dockerfile

tasks:
  # - init: docker-compose down
  #   command: docker-compose up

  - init: pnpm install --frozen-lockfile
    command: |
      export $(cat .env | grep -v "#" | xargs)
      # MONGODB_HOST=localhost ./apps/artemis-web/scripts/wait-for -h localhost -p ${MONGODB_PORT} -t 0
      pnpm build --prod
      # MONGODB_HOST=localhost node apps/artemis-web/scripts/query.js
      npx cypress install
ports:
  - port: 4200
    onOpen: open-browser
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser
  - port: 10000
    onOpen: ignore
